#include <rhbopt.h>

#define TypeDef_Class_Source
#define M_TypeDef_Class_Source

#include <rhbsomir.h>
#include <typedef.ih>

/* this is generated by SOM compiler to access somThis->type
	and messes up accessing 'any' */
#ifdef _type
#undef _type
#endif

SOM_Scope void SOMLINK typedef_somDumpSelf(
	TypeDef SOMSTAR somSelf,
	/* in */ long level)
{
	TypeDef_parent_Contained_somDumpSelf(somSelf,level);
}

SOM_Scope void SOMLINK typedef_somDumpSelfInt(
	TypeDef SOMSTAR somSelf,
	/* in */ long level)
{
	TypeDef_parent_Contained_somDumpSelfInt(somSelf,level);
}

SOM_Scope void SOMLINK typedef_somInit(
	TypeDef SOMSTAR somSelf)
{
	SOM_IgnoreWarning(somSelf);

	TypeDef_parent_Contained_somInit(somSelf);
}

SOM_Scope void SOMLINK typedef__set_type(
	TypeDef SOMSTAR somSelf,
	Environment *ev,
	/* in */ TypeCode type)
{
	SOM_IgnoreWarning(somSelf);
	SOM_IgnoreWarning(ev);
	SOM_IgnoreWarning(type);
}

SOM_Scope TypeCode SOMLINK typedef__get_type(
	TypeDef SOMSTAR somSelf,
	Environment *ev)
{
	TypeCode retVal=NULL;
	somir_containedData *cnd=TypeDef__get_containedData(somSelf,ev);

	if (cnd)
	{
		retVal=cnd->description.typeDesc.type;

		cnd->lpVtbl->Release(cnd);
	}

	return retVal;
}

SOM_Scope void SOMLINK typedef_somUninit(
	TypeDef SOMSTAR somSelf)
{
/*	TypeDefData *somThis=TypeDefGetData(somSelf);*/

	TypeDef_parent_Contained_somUninit(somSelf);
}

SOM_Scope void SOMLINK typedef_somDestruct(
	TypeDef SOMSTAR somSelf,
	boolean doFree,
	somDestructCtrl *ctrl)
{
/*	TypeDefData *somThis;*/
	somDestructCtrl globalCtrl;
	somBooleanVector myMask;

	TypeDef_BeginDestructor

	typedef_somUninit(somSelf);

	TypeDef_EndDestructor
}


SOM_Scope void SOMLINK m_typedef_somDestruct(M_TypeDef SOMSTAR somSelf,boolean doFree,
											somDestructCtrl *ctrl)
{
	somDestructCtrl globalCtrl;
	somBooleanVector myMask;
/*	M_TypeDef *somThis;*/

	M_TypeDef_BeginDestructor;

	M_TypeDef_EndDestructor;
}

SOM_Scope void SOMLINK m_typedef_somDefaultInit(M_TypeDef SOMSTAR somSelf,
											   somInitCtrl *ctrl)
{
	somInitCtrl globalCtrl;
	somBooleanVector myMask;
/*	M_TypeDef *somThis;*/

	M_TypeDef_BeginInitializer_somDefaultInit

	M_TypeDef_Init_M_Contained_somDefaultInit(somSelf,ctrl)
}
