static long Sockets_GetError(long err)
{
	switch (err)
	{
#ifdef _WIN32
#define CASE_ERR(x)		case WSA##x: return SOMS_##x;
#else
#define CASE_ERR(x)		case x: return SOMS_##x;
#endif
	CASE_ERR(EWOULDBLOCK)
	CASE_ERR(EINPROGRESS)
	CASE_ERR(EALREADY)
	CASE_ERR(ENOTSOCK)
	CASE_ERR(EDESTADDRREQ)
	CASE_ERR(EMSGSIZE)
	CASE_ERR(EPROTOTYPE)
	CASE_ERR(ENOPROTOOPT)
	CASE_ERR(EADDRINUSE)
	CASE_ERR(EADDRNOTAVAIL)
	CASE_ERR(ENETDOWN)
	CASE_ERR(ENETUNREACH)
	CASE_ERR(ENETRESET)
	CASE_ERR(ECONNABORTED)
	CASE_ERR(ECONNRESET)
	CASE_ERR(ENOTCONN)
	CASE_ERR(EISCONN)
	CASE_ERR(ESHUTDOWN)
	CASE_ERR(EINTR)
	CASE_ERR(ECONNREFUSED)
	CASE_ERR(EHOSTDOWN)
	CASE_ERR(EHOSTUNREACH)
	}

	return SOMS_UNKNOWNERROR;
}
