#ifndef poid_idl
#define poid_idl
#include <somp.idl>
#include <poida.idl>
interface SOMPIdAssigner;
interface SOMPIdAssigner :
	SOMPIdAssignerAbstract
{
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		dllname = "somp.dll";
		majorversion = 2;
		minorversion = 1;
		filestem = poid;
#ifdef __PRIVATE__
		sompGetSystemAssignedId : override;
		functionprefix = poid_;
#endif
	};
#endif /* __SOMIDL__ */
};
#endif /* poid_idl */
